[package]
name = "stage_two_abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv_tyche = { path = "../riscv_tyche/" }

[features]
visionfive2 = []
