#!/bin/bash

DBG="/tmp/gdb0"
TGT="linux"

print_usage() {
  echo "Expected arguments {linux, rawc} [gdb_socket]"
  echo "With gdb_socket of the form /tmp/gdbX"
  exit 1
}

if [[ "$#" == "0" ]]; then
  print_usage
fi

if [[ "$#" > "2" ]]; then
  print_usage
fi

if [[ "$#" == "2" ]]; then
  DBG="$2"
fi

if [[ "$1" == "linux" ]]; then
  TGT="symbol_linux"
elif [[ "$1" == "rawc" ]]; then
  TGT="symbol_rawc"
else
  print_usage
fi

rust-gdb -q -ex "file target/x86_64-kernel/debug/first-stage" -ex "target remote ${DBG}" -ex "source scripts/tyche-gdb.gdb" -ex "${TGT}"
